#!/bin/bash
# Auto-generated by /auto-loop-spec-long on 2026-05-19
# Spec: spec/spec_pilot_findings_closure_v6.md
# Slug: pilot_findings_closure_v6
# Delay between sessions: 120s
# Stop conditions:
#   - Final Report appears in tracker → break
#   - 'resolution: PENDING' in last 120 lines → break (human blocker)
# Manual stop: tmux kill-session -t autoloop-pilot_findings_closure_v6
#
# Zombie auto-recovery (added 2026-04-29):
#   Before each `claude -p` call, run auto-promote-tracker.py. If it detects
#   a zombie (feat commit Sxx exists, working tree clean, but tracker Current
#   still = Sxx), the script does the bookkeeping in-process and saves
#   ~45min/incident. Wake then continues to fresh Sxx+1.

set -u
cd "$(dirname "spec/spec_pilot_findings_closure_v6.md")/../.." || exit 1

TRACKER=".claude/initiative-tracker-pilot_findings_closure_v6.md"
LOG=".claude/auto-loop-pilot_findings_closure_v6.log"
DELAY=120
SPEC="spec/spec_pilot_findings_closure_v6.md"
INTEGRATION="integration/pilot_findings_closure_v6"
PROMOTE_SCRIPT=".claude/scripts/auto-promote-tracker.py"

while true; do
  if [ ! -f "$TRACKER" ]; then
    echo "=== $(date -u) FATAL: tracker missing, exiting ===" | tee -a "$LOG"
    exit 1
  fi
  FINAL_BODY=$(awk '/^## Final Report/{flag=1;next} flag && /^## /{exit} flag' "$TRACKER" | tr -d '[:space:]')
  FINAL_LEN=${#FINAL_BODY}
  if grep -q '^## Final Report$' "$TRACKER" && \
     ! awk '/^## Final Report/{flag=1;next} flag && /^## /{exit} flag' "$TRACKER" | grep -qE '\(empty|^pending$|^\(pending'; then
    if [ "$FINAL_LEN" -ge 80 ]; then
      echo "=== $(date -u) Final Report populated (${FINAL_LEN} chars body) — initiative done, exiting ===" | tee -a "$LOG"
      break
    fi
  fi
  if tail -120 "$TRACKER" | grep -qE '^[[:space:]]*\*?\*?resolution:\*?\*?[[:space:]]+PENDING[[:space:]]*$'; then
    echo "=== $(date -u) PENDING blocker — exiting for human review ===" | tee -a "$LOG"
    break
  fi

  if [ -x "$PROMOTE_SCRIPT" ]; then
    python3 "$PROMOTE_SCRIPT" "$TRACKER" "$INTEGRATION" 2>&1 | tee -a "$LOG"
    PROMOTE_RC=${PIPESTATUS[0]}
    if [ "$PROMOTE_RC" -eq 0 ]; then
      echo "=== $(date -u) zombie recovered by auto-promote-tracker.py — re-checking stop conditions ===" | tee -a "$LOG"
      continue
    fi
  fi

  echo "=== $(date -u) starting session (fresh context, runtime=loop_wrapper) ===" | tee -a "$LOG"
  timeout 3600 claude -p "/auto-loop-spec $SPEC" \
    --model opus \
    --dangerously-skip-permissions \
    2>&1 | tee -a "$LOG"
  RC=$?
  if [ "$RC" -eq 124 ]; then
    echo "=== $(date -u) WARNING: session hit 1h timeout (rc=124) — wrapper continues ===" | tee -a "$LOG"
  elif [ "$RC" -ne 0 ]; then
    echo "=== $(date -u) NOTE: session exited with rc=$RC ===" | tee -a "$LOG"
  fi
  echo "=== $(date -u) session done, sleeping ${DELAY}s ===" | tee -a "$LOG"
  sleep "$DELAY"
done
